# Project-wide Gradle settings.

# Definições de memória e codificação para o daemon do Gradle
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8

# Ativar paralelismo e cache de compilação para builds mais rápidos
org.gradle.parallel=true
org.gradle.caching=true

# Configurações do AndroidX e Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Configuração para ignorar avisos de APIs descontinuadas do Android (opcional, ajuda a limpar os logs)
android.suppressUnsupportedCompileSdk=34

# Habilitar compilação em árvore (Kotlin)
kotlin.code.style=official
