name: Build Android APK (Manual)

on:
  workflow_dispatch:

jobs:
  build:
    name: Compilar APK Debug
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar e Rodar com Gradle 8.4
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.4'

      # Adicionado --stacktrace para mostrar a linha exata do erro no log
      - name: Compilar com Gradle Detalhado
        run: gradle assembleDebug --no-daemon --stacktrace

      - name: Enviar Artefato do APK (Expira em 24h)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 1
